CREATE TABLE IF NOT EXISTS [gallery_exp].[status](
    [id_status] SMALLINT NOT NULL PRIMARY KEY,
    [status] VARCHAR(10) NOT NULL
) ENCODE AUTO;

CREATE TABLE IF NOT EXISTS [gallery_exp].[users](
    [id_user] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [fk_status] SMALLINT NOT NULL DEFAULT 2,
    [email] VARCHAR(125) NOT NULL,
    [pass] VARCHAR(256) NOT NULL,
    [username] VARCHAR(16) NOT NULL,
    [name] VARCHAR(20) NOT NULL,
    [created_account] TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    [img_profile] VARCHAR(256),
    [apellido_paterno] VARCHAR(30),
    [apellido_materno] VARCHAR(30),
    FOREIGN KEY([fk_status]) REFERENCES [gallery_exp].[status]([id_status])
) ENCODE AUTO;

CREATE TABLE IF NOT EXISTS [gallery_exp].[tags](
    [id_tag] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [name] VARCHAR(50) NOT NULL,
    [description] VARCHAR(100),
    [created_at] TIME NOT NULL,
    [count] BIGINT DEFAULT 0,
    [status] BOOLEAN DEFAULT TRUE
) ENCODE AUTO;

CREATE TABLE IF NOT EXISTS [gallery_exp].[files](
    [id_file] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [fk_user] BIGINT NOT NULL,
    [name_file] VARCHAR(125) NOT NULl,
    [url_file] VARCHAR(256) NOT NULL,
    [sha256] VARCHAR(256) NOT NULL,
    [date_uploaded] TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    [extension_file] VARCHAR(10) NOT NULL,
    [size_file] VARCHAR(100) NOT NULL,
    [status] BOOLEAN DEFAULT TRUE,
    FOREIGN KEY([fk_user]) REFERENCES [gallery_exp].[users]([id_user])
) ENCODE AUTO;

CREATE TABLE IF NOT EXISTS [gallery_exp].[shared_user](
    [id_shared_user] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [fk_file] BIGINT NOT NULL,
    [fk_user] BIGINT NOT NULL,
    [status] BOOLEAN DEFAULT TRUE,
    FOREIGN KEY([fk_file]) REFERENCES [gallery_exp].[files]([id_file]),
    FOREIGN KEY([fk_user]) REFERENCES [gallery_exp].[users]([id_user])
) ENCODE AUTO;

CREATE TABLE IF NOT EXISTS [gallery_exp].[file_tag](
    [id_file_tag] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [fk_file] BIGINT NOT NULL,
    [fk_tag] BIGINT NOT NULL,
    [status] BOOLEAN DEFAULT TRUE,
    FOREIGN KEY([fk_file]) REFERENCES [gallery_exp].[files]([id_file]),
    FOREIGN KEY([fk_tag]) REFERENCES [gallery_exp].[tags]([id_tag])
) ENCODE AUTO;