CREATE TABLE IF NOT EXISTS gallery_exp.tags(
    id_tag BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    created_at DATETIME NOT NULL,
    count BIGINT DEFAULT 0,
    status BOOLEAN DEFAULT TRUE
);