CREATE TABLE IF NOT EXISTS [gallery_exp].[users](
    [id_user] BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    [fk_status] SMALLINT NOT NULL DEFAULT 2,
    [email] VARCHAR(125) NOT NULL,
    [pass] VARCHAR(256) NOT NULL,
    [username] VARCHAR(16) NOT NULL,
    [name] VARCHAR(20) NOT NULL,
    [created_account] TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    [img_profile] VARCHAR(256),
    [apellido_paterno] VARCHAR(30),
    [apellido_materno] VARCHAR(30),
    FOREIGN KEY([fk_status]) REFERENCES [gallery_exp].[status]([id_status])
) ENCODE AUTO;